# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Masonry'

pod 'DateTools', '~> 1.7.0'

target 'JWWeeklySelectDateViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWWeeklySelectDateViewDemo

end
